### ISSUE TITLE
Add support for OpenID connect provider

### ISSUE THREAD

**Issue by ZahiC** [Soluto/agogos#31]
References from tweek:
https://github.com/Soluto/tweek/blob/master/services/gateway/security/authentication.go#L84
https://github.com/Soluto/tweek/blob/master/services/gateway/security/jwkCache.go
https://github.com/Soluto/tweek/blob/master/services/gateway/appConfig/appConfig.go#L62

**Comment by AvivRubys** [comment]
oauth2 is supported now through the UpstreamClientCredentials resource
