### ISSUE TITLE
Extend Schema registry to support additional objects

### ISSUE THREAD

**Issue by Yshayy** [Soluto/agogos#41]
- [ ] Support for additional objects in rest api (policies, endpoints, oidc providers, etc...), maybe use a more generic approach
- [ ] Update grpc to include all objects in response
- [ ] Validate endpoint should support validation of different objects

**Comment by AleF83** [comment]
I purpose to change some names.
I think we should use the same terms Apollo do:

```javascript
const jsSchema = makeExecutableSchema({
  typeDefs,
  resolvers, // optional
  logger, // optional
  allowUndefinedInResolve = false, // optional
  resolverValidationOptions = {}, // optional
  directiveResolvers = null, // optional
  schemaDirectives = null,  // optional
  parseOptions = {},  // optional
  inheritResolversFromInterfaces = false  // optional
});
```

So I want to rename `schemas` to `typeDefs` and to use the term `schema` as the main object that defines the whole GraphQL server configuration.

**Comment by Yshayy** [comment]
Notes from meeting:
1. proto GQLSchemaMessage should be replaced to GQLConfiguration and will include all configuration data, not just schema.
2. Schema registry should be changed just to "registry".
3. It might be useful to define configuration objects in proto and use that definition to create CRUD REST paths and CRDs definition via code generation or runtime tricks.
