### ISSUE TITLE
how to deal with type of Record<string,Object>

### ISSUE THREAD

**Issue by eagelberg** [Soluto/agogos#86]
my api returns a field with dictionary 
the schema look like this: 
```
{
	attributesByType: {
		[type:string]: {
			[key:string]: {
				type: String,
				key: String,
				fields: [String]
			}
		}
	}
}
```

I would like to have some kind of dictionary type or some kind of a mapper on the field. in this case, I would have wanted to return all of the inner values

**Comment by AvivRubys** [comment]
Natively, GraphQL does not have a way to handle Map types. Possible solutions I can think of:
1. Denormalize the data. This way all the data is there, but not indexed. We could consider a `@flatten(levels: 2)` directive to help translate map-based APIs to graphql. It can look like:
```graphql
type Attribute {
  type: String
  key: String
  fields: [String]
}
type Session {
  attributes: [Attribute]
}
```
2. Support a `Map` scalar in agogos. We can look at making it generic, but I'm not sure how feasible that is. This means we would lose all type safety with this solution.
3. Let the user select which attributes he needs. I'm not sure what the use cases for attributes look like, but if, for example, a client will generally be interested in a specific attribute, maybe we could do something like -
```graphql
type Session {
  sessionId: String
  ...other properties...
  attributes(type: String, key: String): [Attribute]
}
```

**Comment by AvivRubys** [comment]
A `JSON` scalar has been added in #94, which is a decent solution for now. Generally I think we prefer the third option, solving this by design rather than by code, but this is a good escape hatch for these kinds of things.
