### ISSUE TITLE
Re-design @http directive

### ISSUE THREAD

**Issue by AvivRubys** [Soluto/agogos#95]
Current:
* Response assumed to always be json
* Serializes "input" arg as the body if it exists
* Different syntax for variable replacement in url and in query/body/headers
```graphql
### DEFINITION
directive @http(
    url: String!
    method: String
    contentType: String # body type. "json" or null
    query: [HttpNameValue!] # key value pairs with arg/source/etc insertion
    body: [HttpNameValue!] # When you want to construct a body with variables from args/source/etc? I think
    timeout: Int
    headers: [HttpNameValue!] # key value pairs with arg/source/etc insertion
) on FIELD_DEFINITION
```

Proposal:
* Introduce `StringMap` scalar that'll just be stringy key-value pairs, to make header/query params easier to use
* Change variable replacement syntax - with inspiration from [apollo](https://www.apollographql.com/docs/link/links/rest/#rest-directive), replace the `:id` syntax with `{source/args/context.id}`
  * No ambiguity about which variable will be inserted
  * Uniform syntax across url, query params and headers for both static and variable-inserted values
* Has feature parity, besides constructing the body from variables from context/source/etc.

```graphql
## DEFINITION
# response is deserialized by content-type
directive @http(
    url: String!
    method: String
    bodyArg: String # The name of the argument to take the body from. defaults to "input"
    bodySerializer: BodySerializers # Request body serialization method. defaults to Json
    headers: StringMap
    query: StringMap
    timeout: Int
) on FIELD_DEFINITION

enum BodySerializers {
    UrlEncoded
    Json
    Xml
}

scalar StringMap

## USAGE:
type Query {
  user(id: ID!, company: String): User @http(url: 'http://myurl/{args.id}`, query: {company: "{args.company}"}, headers: {"x-api-client": "agogos"})
}

type Mutation {
  newUser(input: NewUserInput): User @http(url: 'http://myurl/', bodySerializer: UrlEncoded)
}
```

**Comment by tomeresk** [comment]
LGTM

**Comment by AleF83** [comment]
Looks good! Especially variables.
I need this thing in `@gql` directive too.
So it should be decoupled from `@http` directive.
Maybe it should some native feature of agogos?

**Comment by tomeresk** [comment]
Some changes/clarifications that we discussed today:

- The new directive will be called `@rest`, and the `@http` directive will be gradually deprecated.

- Instead of the `StringMap` scalar, the header/query params will be an `UntypedMap` with string keys and any value (JSON value?).
We might revisit this before the first release of the directive and come up with a more exact definition for the value type

- The `contentType` param will retain its name (instead of `bodySerializer`), but will behave in the new way described for `bodySerializer` (Enum)

**Comment by AvivRubys** [comment]
So `timeout` is also a bit odd. Currently it's in nanoseconds, which seems a little extreme.
I was thinking either making it a string compatible with the [ParseDuration](https://golang.org/pkg/time/#ParseDuration) format like `1s30ms` etc, or changing it to milliseconds outright.

**Comment by tomeresk** [comment]
I agree
Since this is a timeout I don't expect big numbers like hours, so I think we should go with milliseconds

Also how about changing the name to `timeoutMs`?

**Comment by tomeresk** [comment]
I think we also need to set default and maximum timeout values to avoid overloading agogos with connections in case another service is having issues and the caller did not specify a timeout (or set an unreasonably long one).

Maybe a default timeout of 5 seconds and a maximum timeout of 2 minutes?
Also, when someone explicitly sends a timeout longer than the maximum, do we set it to the maximum or return an error? I'm leaning towards returning an error

**Comment by AvivRubys** [comment]
Setting a default timeout is a good idea, but I think 5 seconds is too short.
Gloo defaults to 30 seconds, nginx to 60 seconds.
I think at least 10 seconds is needed, maybe up to 30.

Not sure about setting a maximum, might be better to encounter this in production before optimizing.

**Comment by tomeresk** [comment]
I'll set the default to 10 seconds then and we can do maximum in the future if we see we need it

**Comment by tomeresk** [comment]
The query and header fields will eventually be similar to the previous type, and will look like this:
`[ { name: "field1", value: "value1" }, { name: "field2", value: "value2" } ]`

This is due to the GraphQL spec limiting field names to `/[_A-Za-z][_0-9A-Za-z]*/`, which is too limiting for some required field names (namely headers)
